import React from "react";
import NavBar from "../components/navbar"; // Adjust the import path as necessary
import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from "next";
import { ConvexClientProvider } from "../ConvexClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainHomeLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ConvexClientProvider>
      <div className="h-screen min-h-screen max-h-screen overflow-auto bg-gradient-to-r from-purple-400 via-pink-500 to-red-500">
        <NavBar />
        <div className="flex flex-col w-full h-full">{children}</div>
      </div>
    </ConvexClientProvider>
  );
};

export default MainHomeLayout;
