name: CICD
on:
  push:
    branches:
      - main

env:
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 42.112.26.113
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            if [ ! -d /opt/meme_fe ]; then
              cd /opt
              git clone git@github.com:bichkhe/mammothon-meme-fe.git meme_fe
              git checkout main
            fi

            cd /opt/meme_fe/meme-app
            git pull origin main

            yarn
            nohup yarn dev > /dev/null 2>&1 &
