name: CICD
on:
  push:
    branches:
      - main

env:
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 42.112.26.113
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            CONTAINER_NAME="mammothon_meme_fe"
            if [ ! -d /opt/meme_fe ]; then
              cd /opt
              git clone git@github.com:bichkhe/mammothon-meme-fe.git meme_fe
              git checkout main
            fi

            cd /opt/meme_fe/meme-app
            docker build -t $CONTAINER_NAME:latest .

            # Check if the container exists
            if docker ps -a --filter "name=$CONTAINER_NAME" --format '{{.Names}}' | grep -w $CONTAINER_NAME > /dev/null; then
              echo "Container $CONTAINER_NAME exists."
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
            fi
            docker run -p 5555:5555 -d --name $CONTAINER_NAME $CONTAINER_NAME:latest
